In [3]:
import pandas as pd
file = 'FoodBalanceSheets_E_Africa_NOFLAG.csv'
df = pd.read_csv(file,encoding='latin-1')
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [ ]:

# Answer the following questions based on the African food production dataset provided by the FAO website already provided.

In [53]:
#Question 11
#What is the total sum of Animal Fat produced in 2014 and 2017 respectively?

#Hint: Perform a groupby sum aggregation on ‘Item’

total_sum_of_Animal_Fat_in_2014 = df.groupby('Item')['Y2014'].sum()

total_sum_of_Animal_Fat_in_2017 = df.groupby('Item')['Y2017'].sum()

print(total_sum_of_Animal_Fat_in_2014)
print(total_sum_of_Animal_Fat_in_2017)

# Answer = The total sum of Animal Fat produced in 2014 is 209460.54 and for Year 2017 is 269617.53

Item
Alcohol, Non-Food        2403.00
Alcoholic Beverages    102410.11
Animal Products         11935.65
Animal fats            209460.54
Apples and products      9499.23
                         ...
Vegetables, Other      155038.96
Vegetal Products       107145.19
Wheat and products     232670.13
Wine                     4497.36
Yams                   200396.96
Name: Y2014, Length: 119, dtype: float64
Item
Alcohol, Non-Food        2348.00
Alcoholic Beverages     95581.06
Animal Products         11547.65
Animal fats            269617.53
Apples and products     10198.90
                         ...
Vegetables, Other      157752.59
Vegetal Products       107655.20
Wheat and products     240047.62
Wine                     4178.02
Yams                   229174.59
Name: Y2017, Length: 119, dtype: float64

In [50]:
#Question 12
# What is the mean and standard deviation across the whole dataset for the year 2015 to 3 decimal places?
mean_for_y2015 = df['Y2015'].mean()
print(mean_for_y2015)
std_for_y2015 = df['Y2015'].std()
print(std_for_y2015)

# Answer 
# the mean across the whole dataset for the year 2015 to 3 decimal places is 135.236 
# the standard deviation across the whole dataset for the year 2015 to 3 decimal places is 1603.404

135.23596649549236
1603.4039839423301

In [46]:
#Question 13
# What is the total number and percentage of missing data in 2016 to 2 decimal places?

no_of_missing_data = df['Y2016'].isnull().sum()
print(no_of_missing_data)
percentage_of_missing_data = (df['Y2016'].isnull().sum()/ (df['Y2016'].notnull().sum()+df['Y2016'].isnull().sum())) * 100
print(percentage_of_missing_data.)
#Answer = 1535 and 2.52

1535
2.5187470259094566

In [17]:
#Question 14
# Which year had the highest correlation with ‘Element Code’? 

print(df.corr())

#Answer
# The year 2017 has the highest correlation with ‘Element Code’

              Area Code  Item Code  Element Code     Y2014     Y2015  \
Area Code      1.000000  -0.005159     -0.000209  0.006164  0.005472
Item Code     -0.005159   1.000000     -0.024683  0.021722  0.020857
Element Code  -0.000209  -0.024683      1.000000  0.024457  0.023889
Y2014          0.006164   0.021722      0.024457  1.000000  0.994647
Y2015          0.005472   0.020857      0.023889  0.994647  1.000000
Y2016          0.005247   0.020109      0.023444  0.996081  0.995739
Y2017          0.005006   0.021494      0.024254  0.995230  0.988048
Y2018          0.005665   0.021314      0.024279  0.994872  0.988208

                 Y2016     Y2017     Y2018
Area Code     0.005247  0.005006  0.005665
Item Code     0.020109  0.021494  0.021314
Element Code  0.023444  0.024254  0.024279
Y2014         0.996081  0.995230  0.994872
Y2015         0.995739  0.988048  0.988208
Y2016         1.000000  0.992785  0.992757
Y2017         0.992785  1.000000  0.998103
Y2018         0.992757  0.998103  1.000000

In [44]:
#Question 15
# What year has the highest sum of Import Quantity?

#Hint- Perform a groupby operation on ‘Element’ and use the resulting Dataframe to answer the question
print(df.groupby('Element').sum())

#Y2014 has Import Quantity of 274144.48 
#Y2015 has Import Quantity of 267018.46
#Y2016 has Import Quantity of 286582.78
#Y2017 has Import Quantity of 294559.09 
#Y2018 has Import Quantity of 287997.09 

# Answer
#Year 2017 has highest Import Quantity of 294559.09

                                        Area Code  Item Code  Element Code  \
Element
Domestic supply quantity                   708993   14197445      28068795
Export Quantity                            599910   11840553      26026133
Fat supply quantity (g/capita/day)         675050   13535000       3435732
Feed                                       176272    3538507       7282199
Food                                       663295   13285035      25406622
Food supply (kcal/capita/day)              674057   13511060       3329296
Food supply quantity (kg/capita/yr)        658446   13185401       3163725
Import Quantity                            688174   13795966      28834929
Losses                                     274353    5424803      10292107
Other uses (non-food)                      235554    4729749       8926728
Processing                                 271940    5350416      10313310
Production                                 526751   10450053      21388191
Protein supply quantity (g/capita/day)     675050   13535000       3385502
Residuals                                  623271   12421089      24066350
Seed                                       103537    2035933       4211574
Stock Variation                            571566   11329527      21464704
Total Population - Both sexes                6020     112545         22995
Tourist consumption                         50308    1486528       2869905

                                             Y2014       Y2015       Y2016  \
Element
Domestic supply quantity                1996716.35  2021493.55  2044842.70
Export Quantity                          150020.64   157614.47   151920.46
Fat supply quantity (g/capita/day)        10225.56    10235.74    10102.77
Feed                                     216927.89   225050.22   228958.65
Food                                    1212332.49  1232361.10  1247022.17
Food supply (kcal/capita/day)            454257.00   453383.00   451810.00
Food supply quantity (kg/capita/yr)       49650.63    49345.13    48985.28
Import Quantity                          274144.48   267018.46   286582.78
Losses                                   153223.00   155439.00   157787.00
Other uses (non-food)                     78718.13    66254.41    69563.68
Processing                               282923.00   287929.00   280631.00
Production                              1931287.75  1947019.39  1943537.15
Protein supply quantity (g/capita/day)    11836.46    11833.95    11779.69
Residuals                                 30149.00    30045.00    37224.00
Seed                                      21922.92    23976.82    23389.20
Stock Variation                           58749.83    34910.99    33140.12
Total Population - Both sexes           1031585.00  1058081.00  1085107.00
Tourist consumption                         416.00      349.00       89.00

                                             Y2017       Y2018
Element
Domestic supply quantity                2088198.10  2161192.10
Export Quantity                          182338.80   181594.80
Fat supply quantity (g/capita/day)        10253.84    10258.69
Feed                                     223705.68   233489.68
Food                                    1258888.28  1303841.28
Food supply (kcal/capita/day)            454681.00   455261.00
Food supply quantity (kg/capita/yr)       48690.04    49056.85
Import Quantity                          294559.09   287997.09
Losses                                   160614.00   163902.00
Other uses (non-food)                     91645.97    91300.97
Processing                               292836.00   308429.00
Production                              2030056.89  2075072.89
Protein supply quantity (g/capita/day)    11842.45    11833.56
Residuals                                 35500.00    34864.00
Seed                                      24870.14    25263.14
Stock Variation                           54316.91    20577.91
Total Population - Both sexes           1112641.00  1140605.00
Tourist consumption                          91.00       90.00

In [56]:
#Question 16
# What is the total number of the sum of Production in 2014?

#Hint- Perform a groupby operation on ‘Element’ and use the resulting Dataframe to answer the question
print(df.groupby('Element').sum())

# Answer 
#The total number of the sum of Production in 2014 is 1931287.75

                                        Area Code  Item Code  Element Code  \
Element
Domestic supply quantity                   708993   14197445      28068795
Export Quantity                            599910   11840553      26026133
Fat supply quantity (g/capita/day)         675050   13535000       3435732
Feed                                       176272    3538507       7282199
Food                                       663295   13285035      25406622
Food supply (kcal/capita/day)              674057   13511060       3329296
Food supply quantity (kg/capita/yr)        658446   13185401       3163725
Import Quantity                            688174   13795966      28834929
Losses                                     274353    5424803      10292107
Other uses (non-food)                      235554    4729749       8926728
Processing                                 271940    5350416      10313310
Production                                 526751   10450053      21388191
Protein supply quantity (g/capita/day)     675050   13535000       3385502
Residuals                                  623271   12421089      24066350
Seed                                       103537    2035933       4211574
Stock Variation                            571566   11329527      21464704
Total Population - Both sexes                6020     112545         22995
Tourist consumption                         50308    1486528       2869905

                                             Y2014       Y2015       Y2016  \
Element
Domestic supply quantity                1996716.35  2021493.55  2044842.70
Export Quantity                          150020.64   157614.47   151920.46
Fat supply quantity (g/capita/day)        10225.56    10235.74    10102.77
Feed                                     216927.89   225050.22   228958.65
Food                                    1212332.49  1232361.10  1247022.17
Food supply (kcal/capita/day)            454257.00   453383.00   451810.00
Food supply quantity (kg/capita/yr)       49650.63    49345.13    48985.28
Import Quantity                          274144.48   267018.46   286582.78
Losses                                   153223.00   155439.00   157787.00
Other uses (non-food)                     78718.13    66254.41    69563.68
Processing                               282923.00   287929.00   280631.00
Production                              1931287.75  1947019.39  1943537.15
Protein supply quantity (g/capita/day)    11836.46    11833.95    11779.69
Residuals                                 30149.00    30045.00    37224.00
Seed                                      21922.92    23976.82    23389.20
Stock Variation                           58749.83    34910.99    33140.12
Total Population - Both sexes           1031585.00  1058081.00  1085107.00
Tourist consumption                         416.00      349.00       89.00

                                             Y2017       Y2018
Element
Domestic supply quantity                2088198.10  2161192.10
Export Quantity                          182338.80   181594.80
Fat supply quantity (g/capita/day)        10253.84    10258.69
Feed                                     223705.68   233489.68
Food                                    1258888.28  1303841.28
Food supply (kcal/capita/day)            454681.00   455261.00
Food supply quantity (kg/capita/yr)       48690.04    49056.85
Import Quantity                          294559.09   287997.09
Losses                                   160614.00   163902.00
Other uses (non-food)                     91645.97    91300.97
Processing                               292836.00   308429.00
Production                              2030056.89  2075072.89
Protein supply quantity (g/capita/day)    11842.45    11833.56
Residuals                                 35500.00    34864.00
Seed                                      24870.14    25263.14
Stock Variation                           54316.91    20577.91
Total Population - Both sexes           1112641.00  1140605.00
Tourist consumption                          91.00       90.00

In [111]:
#Question 17
# Which of these elements had the highest sum in 2018?

#Hint-  Select columns ‘Y2018’ and ‘Element’, Perform a groupby operation on ‘Element’ on the 
#selected dataframe and answer the  question.
print(df.groupby('Element')['Y2018'].sum())

# Answer 
# Element with the highest quantity for the year 2018 is Domestic supply quantity.

Element
Domestic supply quantity                  2161192.10
Export Quantity                            181594.80
Fat supply quantity (g/capita/day)          10258.69
Feed                                       233489.68
Food                                      1303841.28
Food supply (kcal/capita/day)              455261.00
Food supply quantity (kg/capita/yr)         49056.85
Import Quantity                            287997.09
Losses                                     163902.00
Other uses (non-food)                       91300.97
Processing                                 308429.00
Production                                2075072.89
Protein supply quantity (g/capita/day)      11833.56
Residuals                                   34864.00
Seed                                        25263.14
Stock Variation                             20577.91
Total Population - Both sexes             1140605.00
Tourist consumption                            90.00
Name: Y2018, dtype: float64

In [62]:
#Question 18
# Which of these elements had the 3rd lowest sum in 2018?

#Hint-  Select columns ‘Y2018’ and ‘Element’, Perform a groupby operation on ‘Element’ on the selected dataframe and answer the  question.
print(df.groupby('Element')['Y2018'].sum())


# Answer 
# The elemnt with 3rd lowest sum in 2018 is = Protein supply quantity (g/capita/day).

Element
Domestic supply quantity                  2161192.10
Export Quantity                            181594.80
Fat supply quantity (g/capita/day)          10258.69
Feed                                       233489.68
Food                                      1303841.28
Food supply (kcal/capita/day)              455261.00
Food supply quantity (kg/capita/yr)         49056.85
Import Quantity                            287997.09
Losses                                     163902.00
Other uses (non-food)                       91300.97
Processing                                 308429.00
Production                                2075072.89
Protein supply quantity (g/capita/day)      11833.56
Residuals                                   34864.00
Seed                                        25263.14
Stock Variation                             20577.91
Total Population - Both sexes             1140605.00
Tourist consumption                            90.00
Name: Y2018, dtype: float64

In [113]:
#Question 19
# What is the total Import Quantity in Algeria in 2018?

print(df.groupby('Element')['Y2018'].sum())

# Answer
# The total Import Quantity in Algeria in 2018 is 36238.29

Element
Domestic supply quantity                  2161192.10
Export Quantity                            181594.80
Fat supply quantity (g/capita/day)          10258.69
Feed                                       233489.68
Food                                      1303841.28
Food supply (kcal/capita/day)              455261.00
Food supply quantity (kg/capita/yr)         49056.85
Import Quantity                            287997.09
Losses                                     163902.00
Other uses (non-food)                       91300.97
Processing                                 308429.00
Production                                2075072.89
Protein supply quantity (g/capita/day)      11833.56
Residuals                                   34864.00
Seed                                        25263.14
Stock Variation                             20577.91
Total Population - Both sexes             1140605.00
Tourist consumption                            90.00
Name: Y2018, dtype: float64

In [25]:
#Question 20
# What is the total number of unique countries in the dataset?

count = len(df['Area'].value_counts())
print(count)

# Answer 
#The total number of unique countries is 49

49